pygments: true
permalink: none
markdown: redcarpet
#sidebar menu config
sidebar:
  - { name: "Welcome", sidebar_name: "welcome", url: "/index.html" }
  - { name: "Installation", sidebar_name: "installation", url: "/documentation/installation.html" }
  - { name: "Configuration", sidebar_name: "configuration", url: "/documentation/configuration.html" }
  - { name: "Development", sidebar_name: "development", subsections:
      [
        { name: "Types", sidebar_name: "development_types", url: "/documentation/development/types/index.html" }
      ]
    }
  - { name: "Features", sidebar_name: "features", subsections:
      [
        { name: "Coupons", sidebar_name: "features_coupons", subsections:
          [
           { name: "About coupons", sidebar_name: "features_coupons_index", url: "/documentation/features/coupons/index.html" },
           { name: "Effects", sidebar_name: "features_coupons_effects", url: "/documentation/features/coupons/effects.html" },
           { name: "Rules", sidebar_name: "features_coupons_rules", url: "/documentation/features/coupons/rules.html" }
          ]
        }
      ]
    }
  - { name: "Modules", sidebar_name: "plugin", subsections: [
       { name: "Starting", sidebar_name: "plugin_index", url: "/documentation/modules/index.html" },
       { name: "Loops", sidebar_name: "plugin_loop", url: "/documentation/modules/loops.html" },
       { name: "TestLoops", sidebar_name: "plugin_testloop", url: "/documentation/modules/testloops.html" },
       { name: "BaseParams", sidebar_name: "plugin_baseparam", url: "/documentation/modules/baseparams.html" },
       { name: "Actions", sidebar_name: "plugin_action", url: "/documentation/modules/actions.html" },
       { name: "Commands", sidebar_name: "plugin_command", url: "/documentation/modules/commands.html" },
       { name: "Routing", sidebar_name: "plugin_routing", url: "/documentation/modules/routing.html" }
      ]
    }
  - { name: "Form", sidebar_name: "form", subsections: [
        { name: "Program you Form", sidebar_name: "form_index", url: "/documentation/form/index.html" },
        { name: "Use your form in actions", sidebar_name: "form_action", url: "/documentation/form/action.html" },
        { name: "Display form", sidebar_name: "form_template", url: "/documentation/form/template.html" }
      ]
    }
  - { name: "Loops", sidebar_name: "loop", subsections: [
        { name: "About loops", sidebar_name: "loop_index", url: "/documentation/loop/index.html" },
        { name: "Accessory loop", sidebar_name: "loop_accessory", url: "/documentation/loop/accessory.html" },
        { name: "Address loop", sidebar_name: "loop_address", url: "/documentation/loop/address.html" },
        { name: "Associated content loop", sidebar_name: "loop_associated_content", url: "/documentation/loop/associated_content.html" },
        { name: "Attribute loop", sidebar_name: "loop_attribute", url: "/documentation/loop/attribute.html" },
        { name: "Attribute availability loop", sidebar_name: "loop_attribute_availability", url: "/documentation/loop/attribute_availability.html" },
        { name: "Attribute combination", sidebar_name: "loop_attribute_combination", url: "/documentation/loop/attribute_combination.html" },
        { name: "Auth loop", sidebar_name: "loop_auth", url: "/documentation/loop/auth.html" },
        { name: "Category loop", sidebar_name: "loop_category", url: "/documentation/loop/category.html" },
        { name: "Content loop", sidebar_name: "loop_content", url: "/documentation/loop/content.html" },
        { name: "Country loop", sidebar_name: "loop_country", url: "/documentation/loop/country.html" },
        { name: "Currency loop", sidebar_name: "loop_currency", url: "/documentation/loop/currency.html" },
        { name: "Customer loop", sidebar_name: "loop_customer", url: "/documentation/loop/customer.html" },
        { name: "Feature loop", sidebar_name: "loop_feature", url: "/documentation/loop/feature.html" },
        { name: "Feature availability loop", sidebar_name: "loop_feature_availability", url: "/documentation/loop/feature_availability.html" },
        { name: "Feature value loop", sidebar_name: "loop_feature_value", url: "/documentation/loop/feature_value.html" },
        { name: "Folder loop", sidebar_name: "loop_folder", url: "/documentation/loop/folder.html" },
        { name: "Image loop", sidebar_name: "loop_image", url: "/documentation/loop/image.html" },
        { name: "Product loop", sidebar_name: "loop_product", url: "/documentation/loop/product.html" },
        { name: "Product sale elements loop", sidebar_name: "loop_product_sale_elements", url: "/documentation/loop/product_sale_elements.html" },
        { name: "Title loop", sidebar_name: "loop_title", url: "/documentation/loop/title.html" }
      ]
    }
  - { name: "Subsitutions", sidebar_name: "substitution", subsections: [
        { name: "Category", sidebar_name: "substitution_category", url: "/documentation/substitutions/category.html" },
        { name: "Content", sidebar_name: "substitution_content", url: "/documentation/substitutions/content.html" },
        { name: "Customer", sidebar_name: "substitution_customer", url: "/documentation/substitutions/customer.html" },
        { name: "Folder", sidebar_name: "substitution_folder", url: "/documentation/substitutions/folder.html" },
        { name: "Product", sidebar_name: "substitution_product", url: "/documentation/substitutions/product.html" }
      ]
    }
